#!/usr/bin/env python3
# 将 /root/dsh/zh/converter/lib/*.js 合并为可在 WebView 运行的 converter.bundle.js
# 输出: assets/converter.bundle.js
import re, sys, os

SRC = "/root/dsh/zh/converter/lib"
MODULES = ["utils", "defaultRule", "cssRule", "jsRule", "urlRule", "rules", "modules", "index"]

out = []
out.append("// Auto-generated by gen-converter-bundle.py — do not edit")
out.append("(function(){")
out.append("var __mods={},__cache={};")
out.append("function __req(n){n=n.replace(/^\\.\\//,'');if(!__cache[n]){__cache[n]={exports:{}};__mods[n](__cache[n],__cache[n].exports,__req);}return __cache[n].exports;}")
for m in MODULES:
    with open(os.path.join(SRC, m + ".js"), "r", encoding="utf-8") as f:
        body = f.read()
    out.append("__mods[%r]=function(module,exports,require){" % m)
    out.append(body)
    out.append("};")
out.append("window.ConverterLib=__req('index');")
out.append("})();")

dst = "/root/dsh/xbsrebuild/assets/converter.bundle.js"
with open(dst, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print("OK", dst, os.path.getsize(dst), "bytes")